### ISSUE TITLE
A17 update?

### ISSUE THREAD

**Issue by kaptain-kavern** [kaptain-kavern/Less-Rebuff#8]
Hi @DingoDjango, I was gone for a while. Hope you're fine and well. 

If you're still around here, do you know if this is needing an A17 update?

**Comment by DingoDjango** [comment]
Hey KK, I dunno but I'm not checking on A17 until its final release since everything is still up for change. My guess is it won't need an update but we could change it to the new patch method for compatibility. Feel free to add me on Steam btw.

**Comment by kaptain-kavern** [comment]
hey thx, 
It was more to take advice from you as well : I was gone a bit and wasn't sure of all the change in A16/A17. 
I will look into it, i'm learning/tinkering with the new patch method ATM ^^

I'm nearly never connected on Steam, I don't own RW on it so i'm never logged. But I will try to remember to add you ⛳️

**Comment by kaptain-kavern** [comment]
I made an A17 version using patchOperation method

https://github.com/kaptain-kavern/Less-Rebuff/tree/dev

**Comment by DingoDjango** [comment]
I haven't had a chance to play around with the patch method but it seems good. I like how it'll combine mods now if they use patches (for example if someone mods the impact and we mod the stack limit).

**Comment by kaptain-kavern** [comment]
Yep i found that very nice too.
_____
So I release the A17 version then.

**Comment by DingoDjango** [comment]
If you want to expand on it in the future I can add an assembly to allow users control over the stack limit, assuming it's as simple as I think it is. RimWorld now has integrated Mod Settings in the vanilla options menu which makes things nice, you don't need HugsLib to have an easy to setup menu any more.

However this will complicate the mod and make it more annoying to maintain, so I'd avoid it at least until the new methods are proven with mass use.
